// Course 3 Data — Yeshua, Paul, and the Torah Question
// Full session content for all 10 sessions

const COURSE_3_DATA = {
  id: 'yeshua-paul-torah-question',
  title: "Yeshua, Paul, and the Torah Question",
  subtitle: "A beginner course on the New Testament passages most often used against Torah",
  weeks: 5,
  sessions: 10,
  level: "Beginner",
  prerequisite: "Courses 1 & 2",
  edition: 'No. 003',
  kicker: 'Course 003 — Intermediate Beginner',
  hero_title_line1: 'Paul did not',
  hero_title_em: 'abolish',
  hero_title_line2: 'Torah.',
  hero_lede: 'Understand the New Testament passages most often used against Torah — by reading Yeshua and Paul in context, in continuity with the whole of Scripture, and without fear.',
  hero_tags: [['5 Weeks',''], ['10 Sessions',''], ['Beginner–Intermediate',''], ['Courses 1 & 2 First','']],
  watermark: 'אֱמֶת',
  syllabus_tagline: 'One apostle. One story.',
  hero_card: {
    hebrew: 'שָׁאוּל',
    transliteration: 'Sha\'ul — Paul',
    tagline: 'apostle · often misread',
    quote: '"The law is holy, and the commandment is holy and righteous and good."',
    ref: '— Romans 7:12'
  },
  pillars: [
    { num: "01", title: "Yeshua does not contradict the Father.", body: "Messiah came to uphold and clarify Torah, not to replace it with a different religion or a different standard of holiness." },
    { num: "02", title: "The New Testament must be read in continuity with earlier Scripture.", body: "No apostolic letter overturns the Torah. Later revelation builds on — and must be tested against — what came before." },
    { num: "03", title: "Grace does not erase holiness.", body: "Grace frees us from condemnation, not from the call to live righteously. Lawlessness is never the fruit of true grace." },
    { num: "04", title: "Paul opposes misuse of Torah, not God's Torah itself.", body: "Paul calls the law holy, just, and good. His debates are about how Torah is misused for justification — not about whether it applies." },
    { num: "05", title: "Justification and obedience are not the same issue.", body: "We are justified by faith, not works. But that same faith produces obedience. Confusing these two questions creates unnecessary contradiction." },
    { num: "06", title: "Context is essential for hard passages.", body: "Difficult Pauline texts must be read in their historical and argumentative setting. A verse pulled from its context can be made to say almost anything." },
  ],
  weeks_data: [
    {
      num: 1,
      title: "Yeshua and the Law",
      subtitle: "What the Master Actually Said and Did",
      memory_verse: { ref: "Matthew 5:19", text: "Therefore whoever relaxes one of the least of these commandments and teaches others to do the same will be called least in the kingdom of heaven, but whoever does them and teaches them will be called great in the kingdom of heaven." },
      sessions: [
        {
          id: 1,
          title: "Did Yeshua Abolish the Torah?",
          big_idea: "Yeshua upheld the Father's instruction and taught it rightly.",
          opening_q: "When someone tells you that Jesus replaced the Old Testament law, what is the first passage they usually quote? What has been your answer?",
          scriptures: ["Matthew 5:17–20", "Matthew 23:1–3", "Mark 7:6–13"],
          teaching: "Matthew 5:17 is one of the most important and most ignored verses in the New Testament. Yeshua says explicitly, plainly, in the clearest possible language: 'Do not think that I came to abolish the Law or the Prophets. I did not come to abolish them but to fulfil them.' He then adds that not one letter of the Torah will pass away until heaven and earth pass away. And then — in case that was still not clear enough — He says that anyone who relaxes even the least commandment and teaches others to do the same will be called least in the kingdom.\n\nThis is not ambiguous. It is direct. And yet it is almost universally read as if Yeshua had said the opposite.\n\nThe confusion often comes from reading 'fulfil' as 'complete and therefore end.' But that is not what the word means in this context. To fulfil the Law and the Prophets means to fill them up with their full meaning — to live them out completely, to demonstrate their true intent, and to restore them from the distortions that had grown up around them. Yeshua was not replacing Torah. He was teaching it correctly.\n\nNotice also who He was confronting in the Gospels. His debates with the Pharisees were not debates about whether to obey God. They were debates about how — specifically, about whether human tradition had replaced or overridden God's actual commands (Mark 7:9–13). Yeshua rebuked tradition that nullified Torah. That is not the same as rebuking Torah.",
          misunderstanding: '"Fulfil means end. Yeshua completed the law so we don\'t have to."',
          response: "If 'fulfil' means 'bring to an end,' then Yeshua's statement in Matthew 5:17 makes no sense — He explicitly contrasts 'fulfil' with 'abolish' as two different options. They cannot be synonyms. Fulfilling means doing completely and correctly, not cancelling. And His warning in verse 19 makes this unmistakable: those who relax the commandments are still accountable.",
          application: "Read Matthew 5:17–20 very slowly, one sentence at a time. For each sentence, ask: Is this what I have been taught this passage means? Write down where your understanding matches the text and where it does not.",
          discussion: ["Why do you think 'fulfil' gets read as 'end' so often?", "How does knowing that Yeshua debated about tradition versus commandment change how you read the Gospels?"],
          homework: ["Summarise in your own words what Yeshua taught about the commandments in Matthew 5:17–20.", "Compare Matthew 5:19 with John 14:15. What do they have in common?", "Write a plain-language response to the claim: 'Jesus fulfilled the law so we don't have to keep it.'"],
        },
        {
          id: 2,
          title: "Love, Obedience, and the Commandments",
          big_idea: "Biblical love does not replace God's commandments — it expresses them.",
          opening_q: "Have you ever heard someone say 'just love God and love people — that's all that matters now'? What did they mean? What do you think they were leaving out?",
          scriptures: ["John 14:15", "John 14:21", "1 John 5:2–3"],
          teaching: "One of the most popular ideas in modern Christianity is that Yeshua reduced all of religion to two commands — love God and love your neighbour — and that everything else is secondary or optional. This is a misreading, and a serious one.\n\nYeshua did say that these two commands are the greatest, and that all the Law and the Prophets hang on them (Matthew 22:37–40). But notice what He said: all the Law and the Prophets hang on them — meaning the Torah is not abolished by these commands; it is expressed through them. The commandments show us what love for God and neighbour looks like in practice.\n\nJohn makes this explicit. In the same Gospel where Yeshua says 'love one another as I have loved you,' he also records Yeshua saying: 'If you love Me, keep My commandments' (John 14:15). And again: 'Whoever has My commandments and keeps them, he it is who loves Me' (14:21). Love and obedience are not competing options. Love is the motive. Obedience is how love expresses itself concretely.\n\nPaul uses the same framework. 'Love is the fulfilment of the law' (Romans 13:10) does not mean love replaces the law. It means love, when genuinely present, carries out what the law requires. A person who truly loves their neighbour will not steal from them, lie to them, or covet what belongs to them — which is exactly what the Torah says.",
          misunderstanding: '"Jesus simplified everything by reducing it to just love. Specific obedience is secondary now."',
          response: "Yeshua did not simplify — He summarised. The two great commands are the foundation on which the whole Torah stands. They do not cancel the Torah; they explain why Torah exists. A person who loves God will want to know what God considers holy, good, and righteous — and that is precisely what the Torah teaches.",
          application: "Read John 14:15–24 carefully. How many times does Yeshua connect love with obedience in this passage? Write down each instance. What does this tell you about how Yeshua understood the relationship between love and commandment-keeping?",
          discussion: ["In what way does Torah define what love looks like concretely?", "Why do you think love and commandments get separated so often in modern Christianity?"],
          homework: ["Find three passages that connect love with obedience to God's commands.", "Write a short response to the claim: 'Love replaces the law.'", "Reflection: What does it mean to love someone in a way that has no specific form or content?"],
        },
      ]
    },
    {
      num: 2,
      title: "Paul, Grace, and Justification",
      subtitle: "Reading the Apostle Without Panic",
      memory_verse: { ref: "Romans 3:31", text: "Do we then overthrow the law by this faith? By no means! On the contrary, we uphold the law." },
      sessions: [
        {
          id: 3,
          title: 'What Does Paul Mean by "Under the Law"?',
          big_idea: '"Under the law" does not mean living in obedience to God.',
          opening_q: 'When you read "you are not under law, you are under grace" in Romans, what does "under law" mean to you? What do you picture?',
          scriptures: ["Romans 6:14–15", "Romans 3:19–20", "Galatians 4:4–5"],
          teaching: "Paul's phrase 'under the law' is one of the most misread expressions in the New Testament. For many readers, it seems to mean simply 'living according to God's commandments.' If that were true, then 'not under law' would mean 'the commandments no longer apply to us.' But that reading collapses the moment you read carefully.\n\nRomans 6:15 reads: 'What then? Shall we sin because we are not under law but under grace? By no means!' Paul is asking: if we are not under law, does that mean we can sin freely? And he answers with the strongest possible no. If 'not under law' meant 'commandments no longer apply,' then Paul's question would make no sense. Why would he even need to ask it?\n\nThe phrase 'under the law' in Paul carries several different senses depending on context:\n\n1. Under the law's condemnation — the law's verdict of guilty hanging over us because of sin. This is removed by Messiah's atoning work.\n2. Under the law as a system for achieving covenant identity — treating Torah-keeping as the ground of justification and acceptance before God.\n3. Under law as opposed to being led by the Spirit — the flesh attempting to fulfil demands it cannot actually meet.\n\nIn none of these senses does 'not under law' mean 'obedience to God is now irrelevant.' Paul himself says he is not under law but is not lawless — he is under the law of Messiah (1 Corinthians 9:21). Grace removes condemnation. It does not remove the call to holiness.",
          misunderstanding: '"Not under law means the commandments simply no longer apply to Christians."',
          response: "Romans 6:15 refutes this directly. Paul asks whether 'not under law' means we can sin, and he says no. If 'not under law' had abolished the relevance of obedience, that question would be meaningless. The phrase means we are not under law's condemnation or as a justification system — not that we are free from the call to live righteously.",
          application: "Read Romans 6:14–23 in full. Mark every place Paul connects freedom from condemnation with the expectation of holy living. Does this passage support or undermine the idea that grace ends the call to obedience?",
          discussion: ["What is the difference between being under law's condemnation and being called to live according to God's instruction?", "Why is it important to ask which sense of 'law' Paul is using before drawing a conclusion?"],
          homework: ["Compare Romans 6:14–15 with Romans 7:12. What does each passage say about the law?", "Paraphrase 'not under law, but under grace' in two or three careful sentences.", "Write a response to: 'Paul says we are not under law, so keeping commandments is optional.'"],
        },
        {
          id: 4,
          title: "Faith, Works, and Justification",
          big_idea: "We are not justified by works of law, but that does not make obedience irrelevant.",
          opening_q: "If someone told you that keeping the Sabbath or eating clean means you are trying to earn your salvation, how would you respond? What is the difference between earning salvation and obeying God?",
          scriptures: ["Romans 3:28", "James 2:17–18", "Ephesians 2:8–10"],
          teaching: "One of the most important distinctions in all of Paul's theology is the distinction between justification and obedience — between how we are declared righteous before God and how we are called to live once we are His people. These are two genuinely different questions, and confusing them causes enormous problems.\n\nJustification is the legal declaration that we stand righteous before God. Paul is emphatic and consistent: we are not justified by 'works of the law.' This is his argument in Romans, Galatians, and Philippians. No amount of Torah-keeping earns us right standing before God. Salvation is by grace through faith. This is not disputed.\n\nBut — and this is crucial — the question of how we are justified is not the same question as how we are called to live. Ephesians 2:8–10 makes this clear in one passage. We are saved by grace through faith, not by works (v.8–9). And yet — for we are His workmanship, created in Messiah for good works, which God prepared beforehand that we should walk in them (v.10). Justification does not produce lawlessness. It produces the freedom and capacity to live rightly.\n\nJames is equally direct. A faith that produces no obedience is not saving faith. 'Faith without works is dead' (James 2:17). The works James speaks of are not the means of justification — they are the fruit and evidence of it.\n\nThe person who says 'keeping Sabbath means trying to earn salvation' has confused the two questions. Obedience is not about earning — it is about responding to the God who has already saved us, in the ways He has told us express love, holiness, and faithfulness.",
          misunderstanding: '"If obedience matters, you must be trying to earn salvation."',
          response: "This confuses two entirely different questions. How are we justified? By faith, not works. How should we live once we are justified? In obedience, as those created for good works. Paul answers both questions consistently. Obedience is not the ground of our standing — it is the fruit of it.",
          application: "Read Ephesians 2:8–10 as one continuous unit. What is the logical movement from verse 8 to verse 10? How do works fit into that movement? Write a paragraph describing what Paul teaches here.",
          discussion: ["Why is it important to distinguish between how we are justified and how we are called to live?", "What does it look like to obey out of love and gratitude rather than to earn standing before God?"],
          homework: ["Define justification, obedience, and legalism in your own words — each in two or three sentences.", "Compare Romans 3:28 with James 2:17–18. How do these passages fit together?", "Write a short response to: 'Torah observance is just trying to earn your way to God.'"],
        },
      ]
    },
    {
      num: 3,
      title: "The Hard Pauline Passages",
      subtitle: "Galatians, Romans, and the Questions Behind Them",
      memory_verse: { ref: "Romans 7:12", text: "So the law is holy, and the commandment is holy and righteous and good." },
      sessions: [
        {
          id: 5,
          title: "Galatians: What Problem Is Paul Actually Addressing?",
          big_idea: "Galatians argues against a distorted use of Torah in relation to justification — not against God's instruction itself.",
          opening_q: "Have you ever been given Galatians as proof that the law is over? Which verses were quoted? Did you have an answer?",
          scriptures: ["Galatians 1:6–9", "Galatians 2:11–14", "Galatians 5:1–4"],
          teaching: "Galatians is probably the most misread book in the New Testament when it comes to Torah. People regularly cite it to prove that the law is finished, that Gentiles have no obligation to obey God's commandments, and that Paul fundamentally rejected Torah. But reading Galatians this way requires ignoring the actual situation the letter was written to address.\n\nPaul opens by telling us there is a specific false gospel being promoted among the Galatian believers (1:6–9). What was it? Certain teachers were insisting that Gentile believers had to be circumcised to be fully accepted by God — that faith in Messiah was not sufficient for covenant standing without taking on the full covenant marker of circumcision as a Gentile entry requirement. This is the problem Paul is confronting.\n\nNotice the specific nature of the controversy. Paul is not arguing against Torah-keeping in general. He is arguing against the use of circumcision as a marker of justification and covenant status for Gentiles — the idea that a Gentile believer must become Jewish through circumcision to be counted fully righteous before God. This is about justification, not about whether obedience matters.\n\nPaul's confrontation with Peter at Antioch (2:11–14) makes the setting concrete. Peter had been eating with Gentile believers but withdrew when certain people arrived from Jerusalem, fearing criticism. Paul rebuked him for this — because Peter's withdrawal implied that Gentile believers were not full members of the community without additional observance. Paul's argument is about social equality and the grounds of acceptance before God — not about whether God's commandments apply.\n\nGalatians 5:3 is often quoted out of context: 'I testify again to every man who accepts circumcision that he is obligated to keep the whole law.' Paul's point here is not that the law is impossible or burdensome. His point is that if you submit to circumcision as a means of justification, you have left the ground of faith — you have committed to a system in which your whole standing before God depends on works. That is the bondage he is warning against.",
          misunderstanding: '"Galatians proves the law is finished for everyone."',
          response: "Galatians is written to a specific community dealing with a specific false teaching — that Gentile believers need circumcision for full covenant standing. Paul's argument is about the grounds of justification, not about whether God's commandments apply to His people. Galatians 5:3 and the surrounding argument make no sense if Torah-keeping is simply irrelevant.",
          application: "Read Galatians 2:11–16 carefully. What is the specific situation? Who are the parties? What is the central dispute? Write a one-paragraph summary of what Paul is actually arguing, in plain language.",
          discussion: ["How does knowing the Galatian situation change your reading of Paul's argument?", "What is the difference between saying 'circumcision is required for justification' and 'God's commandments are good and we should live by them'?"],
          homework: ["Summarise the Galatian controversy in plain language — who was saying what, and why.", "Explain in your own words why context matters so much for reading Galatians.", "Write a short response to a common Galatians prooftext used against Torah."],
        },
        {
          id: 6,
          title: "Romans: Is Paul Against the Law?",
          big_idea: "In Romans, the problem is sin and the flesh — not God's law.",
          opening_q: "If someone quoted Romans 7 to you and said 'Paul proves the law just produces sin and death,' how would you respond? What does Paul actually say about the law in Romans?",
          scriptures: ["Romans 7:7", "Romans 7:12", "Romans 8:3–4"],
          teaching: "Romans is Paul's most systematic theological letter, and it contains some of his most careful statements about Torah. The tragedy is that Romans is regularly mined for isolated phrases — 'not under law,' 'sin reigned through the law,' 'the mind set on the flesh is hostile to God' — without understanding the argument Paul is actually building.\n\nIn Romans 7, Paul addresses a natural objection: if sin came through the law, doesn't that make the law the problem? His answer is unambiguous: 'What shall we say then? That the law is sin? By no means!' (7:7). And a few verses later: 'So the law is holy, and the commandment is holy and righteous and good' (7:12). Paul could not be clearer. The problem is not Torah. The problem is sin — and the flesh that sin works through.\n\nThe flesh takes something that is good (the law), uses it as an occasion for transgression, and produces condemnation. The law itself does not cause this — it merely exposes what is already there. A knife is not responsible for what a murderer does with it. The law is the knife. Sin is the hand.\n\nRomans 8:3–4 gives the resolution. What the law could not do — because the flesh weakened it — God has done by sending His Son. And the purpose? 'In order that the righteous requirement of the law might be fulfilled in us, who walk not according to the flesh but according to the Spirit.' The goal of Messiah's work is that we would fulfil the righteous requirement of Torah. Not that we would be done with it — but that we would live it, by the Spirit, from the inside out.\n\nThis is the exact opposite of the reading that says Paul saw Torah as the enemy. For Paul, Torah is the goal. The Spirit enables what the flesh could not.",
          misunderstanding: '"Romans teaches that the law is the problem and grace is freedom from it."',
          response: "Romans 7:12 says the law is holy, righteous, and good. Romans 8:4 says Messiah came so that the righteous requirement of Torah would be fulfilled in believers. Paul never presents the law as the enemy — he presents sin as the enemy and the law as good instruction that sin distorted.",
          application: "Read Romans 8:1–8 carefully. List every statement Paul makes about the law, about the flesh, and about the Spirit. What does this passage say the Spirit enables us to do? Write down your observations.",
          discussion: ["What is the difference between the law being good and the flesh being unable to fulfil it?", "How does Romans 8:4 change the way you read Paul's 'negative' statements about the law elsewhere?"],
          homework: ["Compare Romans 7:12 with Romans 7:7–13. Write a paragraph explaining Paul's view of the law in this section.", "Explain in plain language why the law is not the problem in Romans.", "Write a short response to: 'Paul says the law produces sin and death, so it's done.'"],
        },
      ]
    },
    {
      num: 4,
      title: "Common Prooftexts Against Torah",
      subtitle: "What These Passages Actually Say",
      memory_verse: { ref: "Romans 6:15", text: "What then? Are we to sin because we are not under law but under grace? By no means!" },
      sessions: [
        {
          id: 7,
          title: '"The Law Was Nailed to the Cross"',
          big_idea: "Messiah's death removes guilt and condemnation — not the definition of righteousness.",
          opening_q: "When someone says 'the law was nailed to the cross,' what do they mean? What do they think that phrase proves? Is that what the passage actually says?",
          scriptures: ["Colossians 2:13–14", "Ephesians 2:15", "Romans 8:3–4"],
          teaching: "Colossians 2:14 is probably the most frequently cited verse in anti-Torah discussions: 'Having cancelled the record of debt that stood against us with its legal demands. This he set aside, nailing it to the cross.' The phrase 'nailed to the cross' is taken to mean that the Torah itself was abolished at Calvary.\n\nBut look at what Paul actually says was cancelled. Not the Torah. Not the commandments. Not the Sabbath or the food laws. What was cancelled was the 'record of debt' — the certificate of debt that stood against us because of our transgressions. The debt is what was nailed to the cross. That debt is our accumulated guilt, the verdict of condemnation that our sin incurred.\n\nThink about what this means. If the law itself was cancelled by the cross, then sin no longer has any definition — because sin is the transgression of law (1 John 3:4). If there is no law, there is no sin. If there is no sin, there is nothing for the cross to deal with. The entire atonement unravels.\n\nThe logic only holds if the standard remains. What was removed was the verdict of guilty hanging over us — not the standard that defined what guilty means. The cross removes condemnation, not holiness. It takes away the record of our debt, not the instruction that shows us what righteousness looks like.\n\nEphesians 2:15 speaks of abolishing 'the law of commandments expressed in ordinances' — but Paul is referring specifically to the dividing wall of hostility between Jew and Gentile: the particular application of Torah's purity code that kept Jews and Gentiles separated at the table. His point is not that Torah has no application — it is that Messiah has made both one people, removing the barrier that kept them divided.",
          misunderstanding: '"The cross cancelled the Torah — all its commands, all its requirements."',
          response: "Colossians 2:14 says the record of debt was cancelled — not the standard that defined the debt. The law shows us what sin is. The cross removes the penalty for sin. These are not the same thing. If the law was cancelled, sin has no definition and the cross is meaningless.",
          application: "Read Colossians 2:13–17 in full. What is Paul speaking about in each verse? What is 'the record of debt'? What is the 'shadow of things to come'? What is he not saying? Write out a careful, sentence-by-sentence summary.",
          discussion: ["What is the difference between removing a debt and removing the standard that defined the debt?", "Why is it important for holiness standards to remain even after condemnation is removed?"],
          homework: ["Make a chart: sin / law / grace / forgiveness / obedience. Write a brief definition of each and explain how they relate.", "Answer three common objections based on Colossians 2 in plain language.", "Reflection: Why does forgiveness of debt make obedience more meaningful rather than less?"],
        },
        {
          id: 8,
          title: "Acts 15, Colossians, and Other Frequently Used Passages",
          big_idea: "Difficult prooftexts must be read in context rather than treated as isolated anti-Torah slogans.",
          opening_q: "Have you ever encountered Acts 15 used as proof that Gentiles only need to keep four rules? Or Colossians 2 used against Sabbath? What did you think at the time?",
          scriptures: ["Acts 15:19–21", "Colossians 2:16–17", "Acts 21:20–24"],
          teaching: "Acts 15 and Colossians 2 are the two passages most frequently deployed against Torah observance among Gentile believers. Both deserve careful, contextual reading.\n\nIn Acts 15, the Jerusalem Council addresses a specific question: must Gentile believers be circumcised as a condition of salvation? The council's answer is no — faith in Messiah is sufficient for justification and entrance into the community. The four basic requirements they list (abstaining from things polluted by idols, from sexual immorality, from things strangled, and from blood) are not meant to be the complete and final summary of what God requires. Verse 21 is crucial and frequently omitted: 'For from ancient generations Moses has had in every city those who proclaim him, for he is read every Sabbath in the synagogues.' The council is not saying 'these four things and nothing else.' They are saying these are the immediate minimum while Gentile believers learn — from the ongoing teaching of Moses in the synagogues every Sabbath.\n\nColossians 2:16–17 is used to argue that Sabbaths and food laws are abolished. But read the context. Paul says 'let no one pass judgment on you in questions of food and drink, or with regard to a festival or a new moon or a Sabbath.' Who is doing the judging? The most natural reading of the Colossian letter is that false teachers were judging the community according to a system that mixed pagan and Jewish elements into a kind of speculative spiritual discipline. Paul is defending the community against these outside critics — he is not telling them to stop observing Torah.\n\nActs 21:20–24 provides a powerful corrective. After years of letter-writing, Paul himself takes a Nazirite vow and undergoes Temple purification — specifically to demonstrate that he has not taught Jewish believers to forsake Torah. If Paul had abandoned Torah, this would have been rank hypocrisy. He was not a hypocrite. He was a Torah-observant Jew who argued against its misuse.",
          misunderstanding: '"Acts 15 limits Gentile obligations to four rules. Colossians clearly ends the Sabbath and food laws."',
          response: "Acts 15:21 shows the four rules were a beginning, not a ceiling — Gentile believers were expected to continue learning from Moses. Colossians 2 addresses outside critics judging the community, not Paul telling them to stop observing Torah. Acts 21 shows Paul personally observed Torah to the end of his known ministry.",
          application: "Read Acts 15:19–21 as one unit. What does verse 21 add to verse 19–20? Why do you think it is so rarely quoted? Write a paragraph on what the full passage teaches.",
          discussion: ["How does Acts 15:21 change your understanding of the council's decision?", "What questions should you ask before drawing conclusions from Colossians 2:16–17?"],
          homework: ["Choose one of these passages and explain its likely context in plain language.", "Write a short response to a common objection based on Acts 15 or Colossians 2.", "List five questions you should ask before concluding that a passage abolishes a commandment."],
        },
      ]
    },
    {
      num: 5,
      title: "A Consistent New Testament Framework",
      subtitle: "How to Read the Whole Bible as One Story",
      memory_verse: { ref: "1 John 2:6", text: "Whoever says he abides in him ought to walk in the same way in which he walked." },
      sessions: [
        {
          id: 9,
          title: "How to Read the New Testament Without Contradicting the Old",
          big_idea: "The New Testament must be read as the continuation of the same story — not the cancellation of it.",
          opening_q: "Before this course, did you read the New Testament as something that built on the Old Testament or as something that largely replaced it? What shaped that view?",
          scriptures: ["Isaiah 8:20", "Luke 16:17", "Romans 15:4"],
          teaching: "There is a principle of biblical interpretation that is ancient, simple, and consistently violated: later texts do not cancel earlier revelation. They develop it, fulfil it, apply it, and deepen it — but they do not contradict it, and they are not tested against it. The earlier text tests the later one.\n\nIsaiah gives this as a standard: 'To the Torah and to the testimony! If they do not speak according to this word, there is no light in them' (8:20). The Torah is the measuring rod. Any teaching, any new development in revelation, must be consistent with what God has already said. This does not mean later revelation adds nothing new. It means new revelation cannot overturn what has already been established.\n\nYeshua uses the same logic. 'It is easier for heaven and earth to pass away than for one stroke of a letter of the Torah to fail' (Luke 16:17). The permanence of Torah is tied to the permanence of creation itself. This is a category statement, not a qualification. Torah does not fail.\n\nPaul writes that everything written in former times was written for our instruction (Romans 15:4). He treats the Hebrew Scriptures as authoritative for his Gentile readers — as a source of doctrine, reproof, correction, and training in righteousness (2 Timothy 3:16). The New Testament never presents the Old as obsolete. It presents it as foundational.\n\nThis means that when a New Testament passage seems to contradict the Torah, the most likely explanation is not that the Torah has been cancelled. It is that the New Testament passage is being misread. We do not resolve apparent tension by discarding the earlier revelation. We resolve it by reading more carefully.",
          misunderstanding: '"The apostles moved beyond Torah. The New Testament has higher authority."',
          response: "The New Testament itself says all Scripture — which at the time meant the Hebrew Scriptures — is breathed out by God (2 Timothy 3:16). Isaiah and Yeshua both treat Torah as the measuring rod against which teaching is tested. No apostle claims to be cancelling Torah. Paul explicitly states that faith upholds the law (Romans 3:31).",
          application: "Find one place in Paul's letters where he explicitly quotes the Hebrew Scriptures to support his argument. What does the way he uses that quotation tell you about how he viewed the authority of the Old Testament?",
          discussion: ["What would it mean to let the Torah test New Testament interpretation rather than the other way around?", "How does reading the New Testament as continuation rather than replacement change how you approach difficult passages?"],
          homework: ["Write a one-page summary: How do Torah, the Prophets, Yeshua, and Paul form one continuous story?", "List three principles you would use to read the Old and New Testaments together without forcing contradiction.", "Explain in plain language why the New Testament does not start from scratch."],
        },
        {
          id: 10,
          title: "Answering New Testament Objections with Wisdom and Confidence",
          big_idea: "You can respond to hard passages without fear, arrogance, or confusion.",
          opening_q: "Which New Testament passage about law and grace has been hardest for you to answer? What made it difficult? How has this course changed how you think about it?",
          scriptures: ["2 Timothy 2:24–25", "1 Peter 3:15", "Colossians 4:6"],
          teaching: "By now you have tools. You know that 'fulfil' does not mean 'end.' You know that 'under law' does not mean 'obedience no longer applies.' You know that the Galatian controversy was about justification, not about whether Torah is good. You know that Colossians 2:14 cancelled the record of debt, not the standard of holiness. You know that Acts 15:21 shows Gentile believers were expected to keep learning from Moses. You know that Paul himself observed Torah through his entire ministry.\n\nThe question now is not whether you have information — you do. The question is how to use it wisely, patiently, and in a way that actually serves the person in front of you.\n\nPaul writes that the servant of the Lord must not be quarrelsome but kind to everyone, patient, correcting opponents with gentleness — in hope that God may grant them repentance and knowledge of the truth (2 Timothy 2:24–25). This is the standard. Not winning the argument. Not impressing people with your knowledge of the Greek. Serving them with kindness and truth.\n\nPeter writes that we should always be prepared to give a defence to anyone who asks — but with gentleness and respect (1 Peter 3:15). The word 'defence' is apologia — a reasoned explanation. That is what you have been building in this course. The character that delivers it must match the truth it carries.\n\nYou do not need to know everything before you speak. You will face passages you cannot fully explain yet. Say so. 'That is a good question and I am not sure I have the full answer, but here is what I do know.' That kind of honesty is more persuasive than false certainty. It is also more faithful.",
          misunderstanding: '"If I cannot answer every difficult verse, I have failed."',
          response: "Faithfulness is not the same as omniscience. Paul himself acknowledged that Peter's — and by extension his own — letters contain things that are hard to understand. Honest limitation, stated with confidence in what you do know, is more credible than pretending to have every answer. Keep studying. Keep walking faithfully. The answers come.",
          application: "Choose one New Testament passage you have struggled to explain. Using everything you have learned in this course, write a short response — as if speaking to a friend who is genuinely asking. Keep it calm, clear, and grounded in Scripture.",
          discussion: ["What does it mean to answer an objection in a way that serves the other person rather than just winning the point?", "How has your confidence in reading Paul changed through this course?"],
          homework: ["Prepare short responses to three New Testament objections you are likely to encounter.", "Write a three-to-five minute explanation of one commonly misunderstood passage.", "Final reflection: How has your view of Yeshua and Paul changed through this course?"],
        },
      ]
    },
  ]
};

Object.assign(window, { COURSE_3_DATA });
